### PR TITLE
Add option to specify external directories for sources

### PR DESCRIPTION
**Pull request by umireon**
This change is required for https://github.com/occ-ai/obs-ocr/pull/12 and should be merged first.

### CODE REVIEW

**Comment by umireon** [comment]
@royshil

**Review by royshil — APPROVED** [review]
this LGTM
however doesn't this requre changing the build.yaml file as well?
it seems to build fine..

**Comment by umireon** [comment]
@royshil I suppose the old implementation of build-linux.sh is broken but it has happened to work.

**Comment by umireon** [comment]
TESSERACT_DIR and LEPTONICA_DIR have default values so that the workflows don't need to be changed.

**Pull request merged**
